project:
  type: website

execute:
  freeze: true

website:
  title: "Pharmaverse Blog"
  site-url: https://pharmaverse.github.io/comms_wg
  repo-url: https://github.com/pharmaverse/comms_wg
  open-graph: true
#  twitter-card:
#    creator: "@djnavarro"
#    card-style: summary_large_image
  navbar:
    background: "#a1d4c6"
    right:
#      - icon: mastodon
#        aria-label: mastodon
#        href: https://fosstodon.org/@djnavarro
      - icon: github
        aria-label: github
        href: https://github.com/pharmaverse/comms_wg
#      - icon: person-circle
#        aria-label: website
#        href: https://djnavarro.net
#      - icon: palette-fill
#        aria-label: art
#        href: https://art.djnavarro.net

format:
  html:
    theme:
      light: [minty, ember.scss]
    #ember.scss
    css: styles.css
 #   include-after-body: plausible.html
preview:
    port: 4200
    browser: false

