project:
  type: website

execute:
  freeze: true
theme: simplex

website:
  title: "pharmaverse blog"
  favicon: media/pharmaverseblog.png
  site-url: https://pharmaverse.github.io/blog
  repo-url: https://github.com/pharmaverse/blog
  open-graph: true
  navbar:
    background: "#CCCCCC"
    right:
      - icon: github
        aria-label: github
        href: https://github.com/pharmaverse/blog
      - text: "Session Info"
        href: session_info.html
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-6ZDR80SCKG"
    anonymize-ip: true      
format:
  html:
    theme:
      light: simplex
    css: styles.css
preview:
    port: 4200
    browser: false

